{
  imports = [
    ./airline.nix
    ./alpha.nix
        ./todo-comments.nix
    ./harpoon.nix
    ./notify.nix
    ./telescope.nix
    ./tmux-navigator.nix
    ./comment.nix
    ./floaterm.nix
    ./obsidian.nix
    ./cmp.nix
    ./transparent.nix
    ./lsp.nix
    ./treesitter.nix
    ./neotree.nix
    ./mini.nix
        ./nixplugin.nix
  ];
}
