#!/usr/bin/env perl

# Read the first line of the "acpi" command output
open (ACPI, "acpi -b | grep 'Battery $bat_number' |") or die;
$acpi = <ACPI>;
close(ACPI);

# Fail on unexpected output
if ($acpi !~ /: (\w+), (\d+)%/) {
    die "$acpi\n";
}

$status = $1;
$percent = $2;
$color = "";

# Set up the full text
$full_text = "<span foreground='#000000' background='#B48EAD'> BAT </span><span foreground='#B48EAD' background='#0f1c21aa'> $percent%</span>";
if ($status eq 'Discharging') {
    # Set color based on percentage
    if ($percent < 20) {
        $color = "#BF616A"; # Red
    }
    else {
        $color = "#859900"; # Green
    }

    # Check for low battery and exit with code 33
    if ($percent < 5) {
        exit(33);
    }

    # Append discharging information
    $full_text .= " <span foreground='#000000' background='$color'> DIS </span>";

    # Append time information
    if ($acpi =~ /(\d\d:\d\d):/) {
        $full_text .= " <span foreground='$color' background='#0f1c21aa'>$1</span>";
    }
} elsif ($status eq 'Charging') {
    # Charging information
    $full_text .= " <span foreground='#000000' background='#859900'> CHR </span>";

    # Append time information to the full text
    if ($acpi =~ /(\d\d:\d\d):/) {
        $full_text .= " <span foreground='#859900' background='#0f1c21aa'>$1</span>";
    }
}

# Set short text
$short_text = $full_text;

# Print text
print "$full_text\n";
print "$short_text\n";

exit(0);

