#!/usr/bin/env bash

echo "<span foreground='#000000' background='#88C0D0'> $(date '+%Y-%m-%d') </span>\
<span foreground='#88C0D0' background='#0f1c21aa'> $(date '+%A') </span>\
<span foreground='#000000' background='#EBCB8B'> $(date '+%I:%M:%S') </span>"
